node {
    stage("checkout") {
        checkout([
                $class                           : 'GitSCM',
                branches                         : [[name: '**']],
                doGenerateSubmoduleConfigurations: false,
                extensions                       : [],
                submoduleCfg                     : [],
                userRemoteConfigs                : [
                        [credentialsId: 'segjjs-gitlab',
                         url          : 'http://212.129.149.40/171250558_teamnamecannotbeempty/backend-webtest.git']
                ]
        ])
    }

    stage("test") {
        sh 'sh backend-main/mvnw clean'
        sh 'sh ./mvnw test -pl backend-main -am -Dmaven.test.failure.ignore=true'
    }
    stage("publish") {
        publishHTML([
                allowMissing         : true,
                alwaysLinkToLastBuild: false,
                keepAll              : false,
                reportDir            : 'backend-main/target/site/jacoco',
                reportFiles          : 'index.html',
                reportName           : 'HTML Report',
                reportTitles         : 'Coverage✨'
        ])
    }
//    stage("docker-build") {
//        sh "docker build -f Dockerfile -t segjjsapp:latest ."
//    }
//    stage("restart") {
//        try {
//            sh 'docker rm -f segjjs'
//        } catch(ignored){
//            echo('Container\'s not running')
//        }
//        sh " docker run -d -p 9090:9090 -v /etc/localtime:/etc/localtime -v /etc/lucene/indexes:/etc/lucene/indexes --link segjjsmysql:segjjsmysql --name segjjs segjjsapp:latest"
//    }
}